### ISSUE TITLE
App stopped working for a repo

### ISSUE THREAD

**Issue by dawhum** [pr-triage/app#131] opened 2019-03-21 13:42 UTC
### Summary

About a week ago, the app stopped working for all repos within our yreceipts organisation. It no longer adds or changes any labels of any pull requests. I can confirm the app is still enabled and authorised.

### Steps to reproduce

For example, request changes on a PR where the app is installed.

### Pull Request URL

For example: https://github.com/yreceipts/yreceipts.com/pull/1809

### What is the current *bug* behavior?

Nothing happens.

### What is the expected *correct* behavior?

A label reflecting the current status of the PR should be added and the previous such label removed when said status changes.

### Relevant logs and/or screenshots

No logs are available, as the app no longer leaves any noticeable traces.

### Possible fixes

N/A

**Comment by maestromac** [comment] 2019-03-21 16:42
It has stopped working for us too. [Recent PRs](https://github.com/thepracticaldev/dev.to/pulls) are untagged. However, `PR: merged` status alone seems to be working 🤔

**Comment by sotayamashita** [comment] 2019-03-24 04:18
I'm sorry for causing you trouble recently. Ithink following PR is might be the cause of the issue. I reverted for now and it works well. 

https://github.com/pr-triage/app/pull/130

**Closed by sotayamashita** 2019-03-24 04:18 UTC

**Comment by maestromac** [comment] 2019-03-25 03:46
Thanks @sotayamashita !

**Comment by allout58** [comment] 2020-02-13 16:45
This started happening for my (private company) repository within the past few days. Should I file a new issue?
